const {
  BASEDIR,
  GET_USER_DATA,
  UPDATE_REFRESH_TOKEN,
  INSERT_USER,
  UDPATE_USER,
  INSERT_DETAILS,
  GET_DETAILS,
  UPDATE_USER_DETAILS,
  DEL_INTEREST_IN_RELATION,
  UPDATE_RELATIONSHIPS,
  INSERT_INTEREST_IN_RELATION,
  GET_INTEREST_IN_RELATION,
  GET_USERS_DATA,
  GET_USER_AUTH
} = require("./constants");

module.exports = {
  BASEDIR,
  GET_USER_DATA,
  UPDATE_REFRESH_TOKEN,
  INSERT_USER,
  UDPATE_USER,
  INSERT_DETAILS,
  GET_DETAILS,
  UPDATE_USER_DETAILS,
  INSERT_INTEREST_IN_RELATION,
  GET_INTEREST_IN_RELATION,
  DEL_INTEREST_IN_RELATION,
  UPDATE_RELATIONSHIPS,
  GET_USERS_DATA,
  GET_USER_AUTH
};
