const { BASEDIR, UPDATE_REFRESH_TOKEN } = require("./constants");
const {
  POST_POSTER,
  GET_ALL_POSTSERS,
  CREATE_CONNECTION,
  GET_ALL_POSTERS_WUSER,
  GET_MY_POSTERS,
  DELETE_POSTER
} = require("./posterQueries");
const {
  GET_GENDER_ID,
  INSERT_POSTER_GENDER,
  GET_ALL_PG
} = require("./genderQueries");
const {
  GET_COUNTRY,
  INSERT_POSTER_REGION,
  GET_ALL_PR
} = require("./regionsQueries");
const {
  GET_USERNAME,
  GET_USER_BY_EMAIL,
  GET_USER_BY_USERNAME,
  GET_USERS_DATA,
  INSERT_USER,
  GET_USER_DATA,
  GET_EMAIL,
  GET_PW_BY_EMAIL,
  UDPATE_USER,
  GET_USER_AUTH,
  GET_UID_BY_EMAIL
} = require("./usersQueries");
const {
  DEL_INTEREST_IN_RELATION,
  UPDATE_RELATIONSHIPS,
  INSERT_INTEREST_IN_RELATION,
  GET_INTEREST_IN_RELATION
} = require("./queries");
const {
  GET_CONNECTION_IDS,
  GET_CONNECTION_WUSER,
  UPDATE_CONNECTION
} = require("./connectionQueries");
module.exports = {
  // User
  GET_EMAIL,
  GET_USERNAME,
  GET_USER_BY_EMAIL,
  GET_USER_BY_USERNAME,
  GET_USER_DATA,
  GET_USERS_DATA,
  INSERT_USER,
  UDPATE_USER,
  GET_PW_BY_EMAIL,
  GET_USER_AUTH,
  GET_UID_BY_EMAIL,
  // Other
  BASEDIR,
  UPDATE_REFRESH_TOKEN,
  INSERT_INTEREST_IN_RELATION,
  GET_INTEREST_IN_RELATION,
  DEL_INTEREST_IN_RELATION,
  UPDATE_RELATIONSHIPS,
  // GENDERS
  GET_GENDER_ID,
  GET_ALL_PG,
  INSERT_POSTER_GENDER,
  // Posters
  POST_POSTER,
  GET_ALL_POSTSERS,
  CREATE_CONNECTION,
  GET_ALL_POSTERS_WUSER,
  GET_MY_POSTERS,
  DELETE_POSTER,
  // REGIONS
  GET_COUNTRY,
  GET_ALL_PR,
  INSERT_POSTER_REGION,
  // CONNECTIONS
  GET_CONNECTION_IDS,
  GET_CONNECTION_WUSER,
  UPDATE_CONNECTION
};
